# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3to-jKiN4Q-NpKqhSb_9l_yn6cMOARs
"""

from bs4 import BeautifulSoup
import urllib3

http = urllib3.PoolManager()

url = "https://www.khanacademy.org/math/algebra-home"
response = http.request('GET', url)
soup = BeautifulSoup(response.data)
word = []
sis = soup.find_all(class_='_dwmetq')
for tag in sis:
    word.append(tag.text.strip())

index = []
for i in range(len(word)):
  index.append(word[i].find(":"))
print(len(index))
topics = {}

for i in range(len(word)):
  if word[i].find(':')!=-1 :
    if not word[i][(index[i]+2):] in topics:
      topics[word[i][(index[i]+2):]] = [word[i][:index[i]]]
    else:
      topics[word[i][(index[i]+2):]].append(word[i][:index[i]])
for key in topics:
  topics[key] = [', '.join(topics[key])]
topics

topics

savee = topics
savee

topics['Complex numbers'].append(['Conic sections'])

#topics['Introduction to algebra'][1] = ['Solving basic equations & inequalities (one variable, linear)', 'Functions', 'Sequences']

for key in topics:
  if len(topics[key]) > 2:
    temp = []
    for i in range(2):
      for j in range(len(topics[key][i+1])):
        temp.append(topics[key][i+1])
    print(temp)
    #topics[key][1] = temp

topics['Series & induction'] = [topics['Series & induction'][0], ['Algebraic modeling']]

for key in topics:
  print("======")
  print(key + " , = " + str(len(topics[key])) + "  \n")
  if len(topics[key]) > 1:
    for i in range(len(topics[key])):
      print(str(topics[key][i]) + "\n")

from google.colab import drive
drive.mount('/content/drive')

import json

with open("/content/drive/MyDrive/tree.json", "w") as outfile:
    json.dump(topics, outfile)